print ("Today's Date?")
Date = input()
print("Breakfast Calories?")
# print("Hello World!") 
print("Breakfast Calories?")
name = input()
print("Hello, " + name)
print ("Calorie Count for")
# print ("Today's Date?")
Date = input()