print ("Today's Date?")
Date = input()
print ("What's your favorite number?")
number = input()
print ("What's your favorite color?")
color = input()
print ("How many countries have you visited?")
countries = input()
print ("Give me a number between 1 and 100")
first_number = int(input())
print ("Give me a second number between 1 and 100")
second_number = int(input())
sum = first_number + second_number
print(sum)